//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technoservice4.DbSingletone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int RequestId { get; set; }
        public string Equipment { get; set; }
        public int EquipmentTypeId { get; set; }
        public int StatusId { get; set; }
        public string ProblemDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public int ClientId { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> MasterId { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Master Master { get; set; }
        public virtual Status Status { get; set; }
    }
}
